# Generated by Django 3.0.1 on 2020-10-03 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('playlist_name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.TextField()),
                ('song_artist', models.TextField()),
                ('song_album', models.CharField(max_length=100)),
                ('song_genre', models.CharField(max_length=100)),
                ('song_rating', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five_stars', models.IntegerField(blank=True)),
                ('four_stars', models.IntegerField(blank=True)),
                ('three_stars', models.IntegerField(blank=True)),
                ('two_stars', models.IntegerField(blank=True)),
                ('one_star', models.IntegerField(blank=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Songs')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSongsMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Playlists')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Songs')),
            ],
        ),
    ]
