# Generated by Django 3.0.1 on 2020-10-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20201003_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrating',
            name='five_stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='songrating',
            name='four_stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='songrating',
            name='one_star',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='songrating',
            name='three_stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='songrating',
            name='two_stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
