# Generated by Django 3.0.1 on 2020-10-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20201003_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='song_url',
            field=models.FileField(default='None', upload_to=''),
        ),
    ]
