# Generated by Django 3.0.1 on 2020-10-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_songs_song_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song_url',
            field=models.FileField(default='None', upload_to='media'),
        ),
    ]
