# Generated by Django 3.0.1 on 2020-10-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20201003_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song_url',
            field=models.FileField(default='None', upload_to=''),
        ),
    ]
