# Generated by Django 3.0.1 on 2020-10-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20201003_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song_url',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
